import { Word, WordType } from './types';

// A seed list of high frequency German words. 
// In a production app, this would be fetched from a database or larger JSON file to reach 2000 words.
export const INITIAL_WORDS: Word[] = [
  { id: '1', german: 'der', spanish: 'el (masculino)', type: WordType.OTHER },
  { id: '2', german: 'die', spanish: 'la (femenino) / los/las (plural)', type: WordType.OTHER },
  { id: '3', german: 'das', spanish: 'el/lo (neutro)', type: WordType.OTHER },
  { id: '4', german: 'und', spanish: 'y', type: WordType.CONJUNCTION },
  { id: '5', german: 'sein', spanish: 'ser/estar', type: WordType.VERB },
  { id: '6', german: 'haben', spanish: 'tener/haber', type: WordType.VERB },
  { id: '7', german: 'ich', spanish: 'yo', type: WordType.OTHER },
  { id: '8', german: 'nicht', spanish: 'no', type: WordType.ADVERB },
  { id: '9', german: 'werden', spanish: 'llegar a ser / convertirse', type: WordType.VERB },
  { id: '10', german: 'sie', spanish: 'ella / ellos / usted', type: WordType.OTHER },
  { id: '11', german: 'Haus', spanish: 'casa', type: WordType.NOUN, gender: 'das' },
  { id: '12', german: 'Auto', spanish: 'coche', type: WordType.NOUN, gender: 'das' },
  { id: '13', german: 'Kind', spanish: 'niño', type: WordType.NOUN, gender: 'das' },
  { id: '14', german: 'Mann', spanish: 'hombre', type: WordType.NOUN, gender: 'der' },
  { id: '15', german: 'Frau', spanish: 'mujer', type: WordType.NOUN, gender: 'die' },
  { id: '16', german: 'essen', spanish: 'comer', type: WordType.VERB },
  { id: '17', german: 'trinken', spanish: 'beber', type: WordType.VERB },
  { id: '18', german: 'groß', spanish: 'grande', type: WordType.ADJECTIVE },
  { id: '19', german: 'klein', spanish: 'pequeño', type: WordType.ADJECTIVE },
  { id: '20', german: 'sehen', spanish: 'ver', type: WordType.VERB },
  { id: '21', german: 'gehen', spanish: 'ir / andar', type: WordType.VERB },
  { id: '22', german: 'Hund', spanish: 'perro', type: WordType.NOUN, gender: 'der' },
  { id: '23', german: 'Katze', spanish: 'gato', type: WordType.NOUN, gender: 'die' },
  { id: '24', german: 'Buch', spanish: 'libro', type: WordType.NOUN, gender: 'das' },
  { id: '25', german: 'Tisch', spanish: 'mesa', type: WordType.NOUN, gender: 'der' },
  { id: '26', german: 'gut', spanish: 'bueno', type: WordType.ADJECTIVE },
  { id: '27', german: 'schlecht', spanish: 'malo', type: WordType.ADJECTIVE },
  { id: '28', german: 'heute', spanish: 'hoy', type: WordType.ADVERB },
  { id: '29', german: 'morgen', spanish: 'mañana', type: WordType.ADVERB },
  { id: '30', german: 'Arbeit', spanish: 'trabajo', type: WordType.NOUN, gender: 'die' },
  { id: '31', german: 'lernen', spanish: 'aprender', type: WordType.VERB },
  { id: '32', german: 'sprechen', spanish: 'hablar', type: WordType.VERB },
  { id: '33', german: 'Stadt', spanish: 'ciudad', type: WordType.NOUN, gender: 'die' },
  { id: '34', german: 'Weg', spanish: 'camino', type: WordType.NOUN, gender: 'der' },
  { id: '35', german: 'Zeit', spanish: 'tiempo', type: WordType.NOUN, gender: 'die' },
  { id: '36', german: 'aber', spanish: 'pero', type: WordType.CONJUNCTION },
  { id: '37', german: 'oder', spanish: 'o', type: WordType.CONJUNCTION },
  { id: '38', german: 'hier', spanish: 'aquí', type: WordType.ADVERB },
  { id: '39', german: 'da', spanish: 'allí / ahí', type: WordType.ADVERB },
  { id: '40', german: 'Freund', spanish: 'amigo', type: WordType.NOUN, gender: 'der' },
  { id: '41', german: 'Wasser', spanish: 'agua', type: WordType.NOUN, gender: 'das' },
  { id: '42', german: 'Brot', spanish: 'pan', type: WordType.NOUN, gender: 'das' },
  { id: '43', german: 'Geld', spanish: 'dinero', type: WordType.NOUN, gender: 'das' },
  { id: '44', german: 'viel', spanish: 'mucho', type: WordType.ADJECTIVE },
  { id: '45', german: 'wenig', spanish: 'poco', type: WordType.ADJECTIVE },
  { id: '46', german: 'neu', spanish: 'nuevo', type: WordType.ADJECTIVE },
  { id: '47', german: 'alt', spanish: 'viejo', type: WordType.ADJECTIVE },
  { id: '48', german: 'leben', spanish: 'vivir', type: WordType.VERB },
  { id: '49', german: 'lieben', spanish: 'amar', type: WordType.VERB },
  { id: '50', german: 'Welt', spanish: 'mundo', type: WordType.NOUN, gender: 'die' }
];
